# Generated by Django 3.2.5 on 2021-07-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='dish_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=400)),
                ('restaurant_email', models.CharField(max_length=400)),
                ('restaurant_mobile_number', models.CharField(max_length=400)),
                ('restaurant_logo', models.ImageField(blank=True, default='media/restaurant_logo/default_logo.png', null=True, upload_to='media/restaurant_logo')),
                ('restaurant_password', models.CharField(max_length=400)),
                ('restaurant_address', models.CharField(max_length=400)),
                ('restaurant_city', models.CharField(max_length=400)),
                ('restaurant_state', models.CharField(max_length=400)),
                ('restaurant_pincode', models.CharField(max_length=400)),
                ('restaurant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.type_of_restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('item_image', models.ImageField(default='item_logo/logo.png', upload_to='item_logo/')),
                ('item_price', models.FloatField(max_length=500)),
                ('dish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish_category')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish_type')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='dish_category',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
